### ISSUE TITLE
☂️ TypeScript 5 + Intellisense

### ISSUE THREAD

**Issue by nandorojo** [nandorojo/dripsy#276]
I think we need to fully rewrite the types for this to start working again. The target would be TS 5.0+ with no backwards compatibility. I'm not exactly looking forward to this lol since getting them working before was such a pain. There are very few tests and stuff. But I'll do my best to get to this at some point soon.

Going to treat this as the umbrella issue for #274 #147 #219 #260 #264 

## Issues

- [x] `sx.variant` gives `string is not assignable to undefined` error
- [x] Field autocomplete stopped working
- [x] `onlyAllowThemeValues` not working #264
- [x] `alignItems: 'center'` doesn't autocomplete, but `alignItems: ['center']` does #174 
- [x] Incorrect `TextInput` types #260 
- [x] `View.variant` gives plain string
- [x] Test `ref`
- [x] Pressable children type is weird
- [x] Use theme values for `TextInput.placeholderTextColor`, `ActivityIndicator.color`, and other related props.
- [x] Move `@dripsy/core` and `@dripsy/gradient` into `dripsy`
- [x] Add custom `theme.aliases` to give your own shorthands

Please let me know what issues I need to add there.

**Comment by nandorojo** [comment]
Released in `4.0.0`: https://github.com/nandorojo/dripsy/releases/tag/v4.0.0

```sh
yarn add dripsy
```
